---
title: "Server setup"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{server-setup}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ""
)
```

```{r, eval = FALSE}

```

## Build time

### Needed R packages

```{r}
library(bigdataclass)
cat(paste0(bdc_libraries(), collapse = "\n"))
```


### Setup the database and create the exercise files

1. Connect to the database *(replace with actual user name and password)*
    ```{r, eval = FALSE}
    con <- dbConnect(RPostgres::Postgres(),
                     host = "localhost",
                     user = "admin_user",
                     port = 5432,
                     password = "password", 
                     dbname = "postgres",
                     bigint = "integer"
                     )
    ```

1. Run the following script
    ```{r, eval = FALSE}
    ## Load the library
    library(bigdataclass)
    ## Path to where the files are to be saved
    folder <- "usr/share/class"
    ## Creates the "retail" schema inside the database connection
    con <- bdc_init_db(con)
    ## Creates the tables and views inside the schema
    bdc_init_database(con = con, avg_daily_orders = 10000)
    ## Builds the files and saves them to the path in "folder" 
    bdc_init_files(con = con, folder = file.path(folder, "files"))
    ## Downloads the books from the Gutenbergh API and saves them to the "folder"
    bdc_init_books(file.path(folder, "books"))
    ```

## Run time

1. Create the project using the following defaults *(replace with actual user name and password)*
    ```{r, eval = FALSE}
    library(bigdataclass)
    folder <- "usr/share/class"
    bdc_create_project(
      folder = "/home/rstudio-user/big-data-class",
      db_connection = "con <- connection_open(RPostgres::Postgres(), host = 'localhost', user = 'user', password = 'pwd', port = 5432,  dbname = 'postgres', bigint = 'integer')",
      dbi_connection = "con <- dbConnect(RPostgres::Postgres(), host = 'localhost', user = 'user', password = 'pwd', port = 5432,  dbname = 'postgres', bigint = 'integer')",
      files_path = file.path(folder, "files"),
      books_path = file.path(folder, "books")
    )
    ```

