```{r setup, include = FALSE}
#knitr::opts_chunk$set(eval = TRUE)
```

```{r include = FALSE}
library(data.table)
library(dtplyr)
library(dplyr)
library(lobstr)
library(ggplot2)

transactions <- fread("../../data/transactions.csv")
```

# Introduction to `dtplyr`

```{r, eval = FALSE}
library(data.table)
library(dtplyr)
library(dplyr)
```

```{r}
dt_mtcars <- lazy_dt(mtcars)
```

```{r}
dt_mtcars %>%
  count(cyl)
```
```{r}
dt_mtcars %>%
  count(cyl) %>%
  collect()
```

```{r, eval = FALSE}
transactions <- fread("data/transactions.csv")
```

```{r}
dt_transactions <- lazy_dt(transactions)
```

```{r}
library(lobstr)
obj_size(transactions)
```

```{r}
obj_size(dt_transactions)
```

```{r}
obj_size(transactions, dt_transactions)
```

```{r}
str(dt_transactions)
```

```{r}
dt_transactions %>%
  count(customer_id)
```

```{r}
dt_transactions %>%
  count(customer_id) %>%
  collect() %>%
  head()
```

```{r}
dt_transactions %>%
  group_by(order_id) %>%
  summarise(
    date = max(order_date),
    no_products = n(),
    total_order = sum(price), 
    customer = max(customer_name)
    )
```

```{r}
orders <- dt_transactions %>%
  group_by(order_id) %>%
  summarise(
    date = max(order_date),
    no_products = n(),
    total_order = sum(price), 
    customer = max(customer_name)
    )

orders
```
```{r}
str(orders)
```

```{r}
orders %>%
  group_by(customer) %>%
  summarise(total = sum(total_order)) %>%
  arrange(desc(total))
```
```{r}
orders %>%
  group_by(customer) %>%
  summarise(total = sum(total_order)) %>%
  ungroup() 
```

